# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Abigail Hsiung
tagline:          'Cognitive Scientist'
description:      'PhD Candidate at Duke University studying how motivational states guide information seeking behaviors. Adapted from <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hsiunga.github.io
baseurl:          /

# Site Author
author:
  name:           'Abigail Hsiung'
  avatar:         # picture 
  # url:            https://twitter.com/mdo
  googlescholar    : "https://scholar.google.com/citations?user=envk7yEAAAAJ&hl=en"
  email            : "abbyhsiung@gmail.edu"
  linkedin         : "abigail-hsiung-85725354"

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
