markdown: kramdown
highlighter: rouge
permalink: pretty
title: Abigail Hsiung
tagline: Cognitive Scientist
description: PhD Candidate in Cognitive Neuroscience at Duke University (she/her/hers)
url: 'http://hsiunga.github.io'
baseurl: /
author:
  name: Abigail Hsiung
  avatar: null
  googlescholar: 'https://scholar.google.com/citations?user=envk7yEAAAAJ&hl=en'
  email: abbyhsiung@gmail.edu
  linkedin: https://www.linkedin.com/in/abigail-hsiung-85725354/
paginate: 5
version: 2.1.0
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
github:
  repo: 'https://github.com/hsiunga/'